import { describe, expect, it } from "vitest";

import { searchCorpus } from "../../src/core/search";

const promotedTerms = [
  "cardiomegaly",
  "gastroenteritis",
  "hyperemia",
  "cystadenoma",
  "anemia",
  "blepharitis",
  "duodenitis",
  "glossitis",
  "glossalgia",
  "blepharoptosis",
  "blepharospasm",
  "bursitis",
  "encephalitis",
  "encephalomalacia",
  "enterocolitis",
  "cyanosis",
  "colitis",
  "dacryocystitis",
  "endometriosis",
  "encephalomyelitis",
  "bronchiolitis",
  "enterotoxemia",
  "hyperalgesia",
  "encephalocele",
  "hypercapnia",
  "hyperhidrosis",
  "acrodermatitis",
  "arthrogryposis",
  "ankylosis",
  "endometritis",
  "acromegaly",
  "acrodynia",
  "adenofibroma",
  "fibrosarcoma",
  "adenolymphoma",
  "hemangiosarcoma",
  "angiokeratoma",
  "hematoma",
  "hematocele",
  "hematuria",
  "cholecystitis",
  "colic",
  "gliosis",
  "adenocarcinoma",
  "ganglioneuroma",
  "glioma",
  "glioblastoma",
  "carcinoma",
  "carcinosarcoma",
  "fibroma",
  "fibromyalgia",
  "fibrosis",
  "hemangioma",
  "hemarthrosis",
  "anuria",
  "cystadenocarcinoma",
  "arteriosclerosis",
  "albuminuria",
  "bronchopneumonia",
  "chondroblastoma",
  "chondrosarcoma",
  "chondroma",
  "achondroplasia",
  "aortitis",
  "appendicitis",
  "hemothorax",
  "anaplasia",
  "aphakia",
  "aphasia",
  "fasciitis",
  "cholestasis",
  "hemiplegia",
  "aphonia",
  "apnea",
  "dyspnea",
  "glomerulonephritis",
  "epiglottitis",
  "dystonia",
  "dyspepsia",
] as const;

describe("promoted term search", () => {
  it.each(promotedTerms)(
    "Given promoted term %s, when searched exactly, then it resolves as a verified term",
    (term) => {
      const result = searchCorpus({ query: term })[0];

      expect(result).toMatchObject({
        kind: "term",
        id: `term:${term}`,
        matchedBy: { kind: "exact", field: "term", value: term },
      });
    },
  );
});
