import Link from "next/link";

import { PageHeading } from "../../components/page-heading";
import { StatusPanel } from "../../components/status-panel";
import { createPageMetadata } from "../../lib/metadata";

export const metadata = createPageMetadata("Methodology", "Understand corpus records, local segmentation, result statuses, citations, and limitations.", "/methodology/");

const resultBases = [
  ["Verified entry", "An authored canonical term or source-cited alias supplies the displayed primary analysis."],
  ["Constructed from known parts", "The local analyzer covers the full normalized input with known parts, but no authored term record exists."],
  ["Partial match", "Known parts are ordered with literal unresolved spans. No meaning is invented for unresolved characters."],
  ["Unsupported", "The input is empty, too long, contains multiple words or unsupported characters, or has no known parts."],
] as const;

export default function MethodologyPage() {
  return <div className="page-sheet"><PageHeading overline="Editorial and computational method" title="Methodology"><p>This static field guide supports terminology learning and reference. It does not diagnose, interpret symptoms, recommend treatment, or replace clinical guidance.</p></PageHeading><StatusPanel tone="privacy" label="Not medical advice"><p>Analyze terminology only. Do not enter names, symptoms, record identifiers, or private medical information.</p></StatusPanel><section aria-labelledby="corpus-heading"><div className="section-heading"><p className="overline">01 / Corpus model</p><h2 id="corpus-heading">Authored records first</h2></div><p>Versioned local data defines sources, word parts, canonical terms, aliases, authored analyses, and term relationships. The production build validates references and generates static indexes before pages are exported.</p></section><section aria-labelledby="basis-heading"><div className="section-heading"><p className="overline">02 / Result basis</p><h2 id="basis-heading">Four explicit outcomes</h2></div><dl className="basis-grid">{resultBases.map(([term, description]) => <div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl></section><section aria-labelledby="segment-heading"><div className="section-heading"><p className="overline">03 / Segmentation</p><h2 id="segment-heading">Order, coverage, and transformations</h2></div><p>The analyzer normalizes one supported word and ranks candidate segmentations deterministically. Every resolved segment keeps source offsets. A recorded transformation, such as dropping a terminal combining vowel before a suffix, is shown rather than silently applied.</p><p>Confidence describes coverage and authorship basis, not medical certainty.</p></section><section aria-labelledby="limits-heading"><div className="section-heading"><p className="overline">04 / Limitations</p><h2 id="limits-heading">What this guide does not claim</h2></div><ul className="ruled-list"><li>The corpus is intentionally small and does not cover every medical term.</li><li>A computational construction is not an etymological or clinical conclusion.</li><li>Listed meanings and relationships stay within authored records.</li><li>External citations document provenance and may change outside this project.</li></ul></section><section id="corrections" aria-labelledby="corrections-heading"><div className="section-heading"><p className="overline">05 / Corrections</p><h2 id="corrections-heading">Evidence-backed public issues</h2></div><p>Term and part pages prepare a GitHub issue with the current record, fields for a proposed change, and an evidence request. GitHub issues are public. Never include names, symptoms, record numbers, or other private medical information.</p><p><Link href="/sources/">Review the source ledger</Link> before proposing a correction.</p></section></div>;
}
